url: http://legal-united.com
baseurl: /legalunited

# Site settings
title: Legal United
email: info@legal-united.com
description: "I'm Jantine de Bree. A lawyer based in Amsterdam. Let me help you manage your Intellectual Property and terms and conditions."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jantine de Bree
  pic: 1
  position: Lawyer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: Prinsengracht
  - line: Amsterdam, The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
